### ISSUE TITLE
Not compatible with MariaDB

### ISSUE THREAD

**Issue by Rakambda** [paulgreg/rsstodolist-node-server#24]
Hello,
It seems that recently a change (8a7c9125466de2c2c99f6659ed3f21ae19385a4d) has been made that makes it uncompatible with MariaDB even though it is marked as compatible with it in the readme. (Using MariaDB version 10.11.8).

```
rss-todo-list  | Error
rss-todo-list  |     at Query.run (/usr/app/node_modules/sequelize/lib/dialects/mariadb/query.js:53:25)
rss-todo-list  |     at /usr/app/node_modules/sequelize/lib/sequelize.js:315:28
rss-todo-list  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
rss-todo-list  |     at async MySQLQueryInterface.select (/usr/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
rss-todo-list  |     at async feeds_feedentry.findAll (/usr/app/node_modules/sequelize/lib/model.js:1140:21) {
rss-todo-list  |   name: 'SequelizeDatabaseError',
rss-todo-list  |   parent: SqlError: (conn:3543, no: 1064, SQLState: 42000) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULLS LAST, `feeds_feedentry`.`createdAt` DESC LIMIT 25' at line 1
rss-todo-list  |   sql: SELECT `id`, `name`, `url`, `title`, `description`, `createdAt`, `updatedAt` FROM `feeds_feedentry` AS `feeds_feedentry` WHERE `feeds_feedentry`.`name` = 'rakambda' ORDER BY `feeds_feedentry`.`updatedAt` DESC NULLS LAST, `feeds_feedentry`.`createdAt` DESC ... - parameters:[]
rss-todo-list  |       at module.exports.createError (/usr/app/node_modules/mariadb/lib/misc/errors.js:66:10)
rss-todo-list  |       at PacketNodeEncoded.readError (/usr/app/node_modules/mariadb/lib/io/packet.js:579:19)
rss-todo-list  |       at Query.readResponsePacket (/usr/app/node_modules/mariadb/lib/cmd/parser.js:62:28)
rss-todo-list  |       at PacketInputStream.receivePacketBasic (/usr/app/node_modules/mariadb/lib/io/packet-input-stream.js:85:9)
rss-todo-list  |       at PacketInputStream.onData (/usr/app/node_modules/mariadb/lib/io/packet-input-stream.js:135:20)
rss-todo-list  |       at Socket.emit (node:events:519:28)
rss-todo-list  |       at addChunk (node:internal/streams/readable:559:12)
rss-todo-list  |       at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
rss-todo-list  |       at Readable.push (node:internal/streams/readable:390:5)
rss-todo-list  |       at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
rss-todo-list  |     sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULLS LAST, `feeds_feedentry`.`createdAt` DESC LIMIT 25' at line 1",
rss-todo-list  |     sql: "SELECT `id`, `name`, `url`, `title`, `description`, `createdAt`, `updatedAt` FROM `feeds_feedentry` AS `feeds_feedentry` WHERE `feeds_feedentry`.`name` = 'rakambda' ORDER BY `feeds_feedentry`.`updatedAt` DESC NULLS LAST, `feeds_feedentry`.`createdAt` DESC LIMIT 25;",
rss-todo-list  |     fatal: false,
rss-todo-list  |     errno: 1064,
rss-todo-list  |     sqlState: '42000',
rss-todo-list  |     code: 'ER_PARSE_ERROR',
rss-todo-list  |     parameters: undefined
rss-todo-list  |   },
rss-todo-list  |   original: SqlError: (conn:3543, no: 1064, SQLState: 42000) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULLS LAST, `feeds_feedentry`.`createdAt` DESC LIMIT 25' at line 1
rss-todo-list  |   sql: SELECT `id`, `name`, `url`, `title`, `description`, `createdAt`, `updatedAt` FROM `feeds_feedentry` AS `feeds_feedentry` WHERE `feeds_feedentry`.`name` = 'rakambda' ORDER BY `feeds_feedentry`.`updatedAt` DESC NULLS LAST, `feeds_feedentry`.`createdAt` DESC ... - parameters:[]
rss-todo-list  |       at module.exports.createError (/usr/app/node_modules/mariadb/lib/misc/errors.js:66:10)
rss-todo-list  |       at PacketNodeEncoded.readError (/usr/app/node_modules/mariadb/lib/io/packet.js:579:19)
rss-todo-list  |       at Query.readResponsePacket (/usr/app/node_modules/mariadb/lib/cmd/parser.js:62:28)
rss-todo-list  |       at PacketInputStream.receivePacketBasic (/usr/app/node_modules/mariadb/lib/io/packet-input-stream.js:85:9)
rss-todo-list  |       at PacketInputStream.onData (/usr/app/node_modules/mariadb/lib/io/packet-input-stream.js:135:20)
rss-todo-list  |       at Socket.emit (node:events:519:28)
rss-todo-list  |       at addChunk (node:internal/streams/readable:559:12)
rss-todo-list  |       at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
rss-todo-list  |       at Readable.push (node:internal/streams/readable:390:5)
rss-todo-list  |       at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
rss-todo-list  |     sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULLS LAST, `feeds_feedentry`.`createdAt` DESC LIMIT 25' at line 1",
rss-todo-list  |     sql: "SELECT `id`, `name`, `url`, `title`, `description`, `createdAt`, `updatedAt` FROM `feeds_feedentry` AS `feeds_feedentry` WHERE `feeds_feedentry`.`name` = 'rakambda' ORDER BY `feeds_feedentry`.`updatedAt` DESC NULLS LAST, `feeds_feedentry`.`createdAt` DESC LIMIT 25;",
rss-todo-list  |     fatal: false,
rss-todo-list  |     errno: 1064,
rss-todo-list  |     sqlState: '42000',
rss-todo-list  |     code: 'ER_PARSE_ERROR',
rss-todo-list  |     parameters: undefined
rss-todo-list  |   },
rss-todo-list  |   sql: "SELECT `id`, `name`, `url`, `title`, `description`, `createdAt`, `updatedAt` FROM `feeds_feedentry` AS `feeds_feedentry` WHERE `feeds_feedentry`.`name` = 'rakambda' ORDER BY `feeds_feedentry`.`updatedAt` DESC NULLS LAST, `feeds_feedentry`.`createdAt` DESC LIMIT 25;",
rss-todo-list  |   parameters: {}
rss-todo-list  | }
```

Running the query manually without the `NULLS LAST` works fine.
Maybe instead of using this apparently vendor specific keyword, something like 
```sql
ORDER BY
ISNULL(`feeds_feedentry`.`updatedAt`), -- Makes NULL values be sorted after defined values, sort DESC to make them first
`feeds_feedentry`.`updatedAt` DESC,
`feeds_feedentry`.`createdAt` DESC
LIMIT 25;
```
could be used.

**Comment by paulgreg** [comment]
Indeed, I switch recently to PostgreSQL by default and behavior with NULL columns was different which made me changes that. I tought it will still works with MariaDB.
Thanks for the issue.
I’ll try to fix it to handle both DB.
Feel free to open a merge request if you’ve got a working solution. I could then try it it with postgres.

**Comment by Rakambda** [comment]
Tried to play a bit with it, but I'm not familiar with sequelize at all.

To sum it up: 

* `NULLS LAST` is not compatible with MariaDB.
* Above I suggested `ISNULL(xxx)` but looking a bit into docs it seems that it isn't the same function on Postgres.
* Could have used something like `CASE WHEN updatedAt IS NULL THEN 1 ELSE 0 ASC` but this looks a bit bulky for the job and doesn't seem to play well with sequelize as it'd require a `literal`.
* Last idea, which I implemented, is to use a COALESCE which should be pretty standard everywhere and set NULLs to an arbitrary "early date" so that they should be last in a normal scenario

This seems to work on MariaDB, I'll let you make sure for the Postgres part.

**Comment by paulgreg** [comment]
Thanks for that PR.
I’ve tried another approach in #26 where I’m determining dialect to add `NULLS LAST` only if postgres. It’s maybe less invasive. 
What do you think ?

**Comment by Rakambda** [comment]
That works too, whatever you prefer is fine by me, I'm not that familiar with the codebase nor the libs used. Though I agree that your version seems to be using less "aggressive" methods. By that I mean that it doesn't rely on `sequelize.fn` which kinda invokes a "random" method on the DB.

**Comment by paulgreg** [comment]
Ok. I’ll merge the « dialect » solution.
